In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/forward_analytics_results/companydataset_peopledata.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18489769 entries, 0 to 18489768
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   NAME      object
 1   INDUSTRY  object
 2   SIZE      object
dtypes: object(3)
memory usage: 423.2+ MB

In [ ]:
#sampled_df = df.sample(n = 1000000, random_state=42)

In [ ]:
#sampled_df = sampled_df[["NAME", "INDUSTRY"]]

In [ ]:
#sampled_df

In [ ]:
def mappig_industry(data):

  # Define the broader industry categories as a mapping dictionary
  industry_mapping = {
      # Technology & IT
      "information technology and services": "Technology & IT",
      "computer software": "Technology & IT",
      "internet": "Technology & IT",
      "telecommunications": "Technology & IT",
      "graphic design": "Technology & IT",


      # Healthcare & Wellness
      "medical practice": "Healthcare & Wellness",
      "hospital & health care": "Healthcare & Wellness",
      "health, wellness and fitness": "Healthcare & Wellness",
      "pharmaceuticals": "Healthcare & Wellness",

      # Food & Hospitality
      "restaurants": "Food & Hospitality",
      "food & beverages": "Food & Hospitality",
      "food production": "Food & Hospitality",
      "hospitality": "Food & Hospitality",
      "leisure, travel & tourism": "Food & Hospitality",

      # Finance
      "financial services": "Finance",
      "investment management": "Finance",

      # Legal
      "law practice": "Legal",
      "legal services": "Legal",

      # Retail & Consumer Goods
      "retail": "Retail & Consumer Goods",
      "wholesale": "Retail & Consumer Goods",
      "consumer goods": "Retail & Consumer Goods",
      "apparel & fashion": "Retail & Consumer Goods",

      # Construction & Real Estate
      "construction": "Construction & Real Estate",
      "real estate": "Construction & Real Estate",
      "building materials": "Construction & Real Estate",
      "architecture & planning": "Construction & Real Estate",

      # Education & Training
      "education management": "Education & Training",
      "higher education": "Education & Training",
      "professional training & coaching": "Education & Training",
      "e-learning": "Education & Training",

      # Manufacturing & Engineering
      "mechanical or industrial engineering": "Manufacturing & Engineering",
      "electrical/electronic manufacturing": "Manufacturing & Engineering",
      "machinery": "Manufacturing & Engineering",
      "civil engineering": "Manufacturing & Engineering",

      # Transportation & Logistics
      "transportation/trucking/railroad": "Transportation & Logistics",
      "logistics and supply chain": "Transportation & Logistics",
      "automotive": "Transportation & Logistics",

      # Media, Entertainment & Arts
      "media production": "Media, Entertainment & Arts",
      "entertainment": "Media, Entertainment & Arts",
      "photography": "Media, Entertainment & Arts",
      "publishing": "Media, Entertainment & Arts",

      # Government & Non-Profit
      "government administration": "Government & Non-Profit",
      "non-profit organization management": "Government & Non-Profit",
      "religious institutions": "Government & Non-Profit",
      "civic & social organization": "Government & Non-Profit",

      # Environmental Services & Agriculture
      "environmental services": "Environmental Services & Agriculture",

      # Resources
      "mining & metals": "Resources",
      "farming": "Resources",
      "forestry": "Resources",

      # Energy
      "oil & energy": "Energy",
      "renewables & environment": "Energy",
      "utilities": "Energy",

      # Business Services
      "management consulting": "Business Services",
      "business supplies and equipment": "Business Services",
      "human resources": "Business Services",
      "staffing and recruiting": "Business Services",
      "accounting": "Business Services",
  }
  data.loc[:, 'INDUSTRY_GROUP'] = data['INDUSTRY'].map(industry_mapping).fillna('Other')

  return data

In [ ]:
mapped_df = mappig_industry(df)

In [ ]:
mapped_df.value_counts("INDUSTRY_GROUP")

INDUSTRY_GROUP
Other                                   5036108
Construction & Real Estate              2102513
Technology & IT                         1631008
Food & Hospitality                      1410367
Retail & Consumer Goods                 1410332
Healthcare & Wellness                   1173763
Business Services                       1096167
Education & Training                     778878
Manufacturing & Engineering              654984
Government & Non-Profit                  601609
Media, Entertainment & Arts              561502
Finance                                  527814
Transportation & Logistics               498202
Legal                                    367599
Energy                                   268536
Resources                                225344
Environmental Services & Agriculture     145043
Name: count, dtype: int64

In [ ]:
# Define unecessary suffixes
removal_list=['plc','inc', 'ltd', 'lp', 'llc', 'limited','pjsc', 's', 'group', 'the', 'of', 'a',
         'de', 'and', 'co', 'l', 'gmbh', 'o', 'company', 'e', 'r', 'pvt', 'c', 'b',
          'incorporated', 's.a.', 'oy','kg','sarl','sl','nv','kk','kabushiki kaisha','oyj','aps','kft','sp. z o.o.','zrt',
         'for', 'v', 'd', 'p', 'm', 'an','thermal','n', 'china','pty', 'srl', 'it',
         'in', 'i', 'la', 'pt', 'llp', 'st', 'do', 'sa', 'ab', 'spa', 'ag', 'ltda',
         'foundation', 't', 'as', 'bv', 'y', 'uk', 'corp','corporation','industry',
         'holding', 'environmental', 'generation', 'protection', 'branch',
         'anhui','huadian','wuhu', "lu'an", 'suzhou', 'new', 'holdings', 'jsc', 'district',
         'city', 'state', 'mongolia', 'industrial', 'enterprise', 'county','owned',
         'shandong', 'shandong', 'xinjiang', 'beijing', 'guizhou', 'government',
         'partnership', 'shanghai',  'capital', 'center', 'bureau', 'jiangsu', 'commission', 'people',
         'datang','shenzhen', 'ordos', 'biomass', 'chongqing', 'special',
         'zhungeer', 'banner', 'yaogou', 'dawei', 'beijing jingneng',
         'to be determined', 'bazhong', 'huaneng', 'plant', 'future', 'times',
         'guangdong', 'xinxing', 'guangdong', 'guangxin',
         'guangrao', 'hengtai', 'guangxi', 'beibu', 'baise', 'bobai', 'yantao',
         'fund partnership', 'yulin', 'haofeng', 'tianjin',
         'fujian', 'zhejiang', 'ningxia', 'guoneng', 'shanxi', 'henan',
         'shenmu', 'hebei', 'shaanxi','sichuan', 'municipal',
         'jilin', 'port', 'fugu', 'datong', 'yunnan',
          'national', 'industries', 'green', 'urban', 'zone', 'committee', 'retim',
         'no', 'north', 'ningbo', 'coking', 'guodian','hong', 'kong',
         'changzhi', 'guangzhou', 'qingdao', 'natural', 'tangshan',
          'union', 'partners', 'province', 'economic', 'united',
         'hangzhou', 'everbright', 'town','ve', 'bhd', 'south', 'heilongjiang',
         'bara', 'enterprises', 'general', 'park', 'authority', 'public',
          'trust', 'lu', 'venture', 'hubei', 'liaoning',
          'indonesia', 'water', 'provincial', 'central', 'creek',
          'east', 'products', 'shuozhou', 'shenhua', 'dongguan', 'australia', 'global', 'yangquan',
          'razrez', 'coke', 'hunan', 'hainan', 'cv', 'prima', 'jaya', 'ticaret',
          'yangcheng', 'sdn', 'wuhan', 'west', 'joint', 'high',
              'tbk', 'jiangmen', 'jinneng', 'gansu', 'j', 'pacific', 'autonomous', 'zhengzhou', 'dalian',
              'grupo', 'utama', 'river', 'kaidi', 'grid', 'gaoping', 'blue', 'sinopec', 'southern', 'w',
              'jungar', 'pte', 'jiangxi', 'shenyang', 'clean', 'real', 'minerals', 'asia', 'del', 'dongying',
              'nanjing', 'sanayi', 'mines', 'stainless', 'lingshi', 'generating', 'linyi', 'cooperative', 'xiamen', 'k',
              'taiyuan', 'jincheng', 'fuel', 'zibo', 'village', 'jinmei', 'wuhai', 'office', 'colombia', 'erdos', 'luoyang', 'guoxin',
               'area', 'jiangyin', 'al',  'baotou', 'sugar', 'g', 'jizhong', 'ao', 'mountain', 'mandiri', 'liulin', 'bioenergia', 'alam',
               'zhuhai', 'xi', 'doo', 'rural', 'el', 'xuzhou', 'turbine', 'metallurgical',
              'jianlong', 'black', 'zhangjiagang', 'changchun', 'fenxi', 'zheneng', 'pinglu',
              'brasil', 'xinzhou', 'qinghai', 'india', 'bumi', 'madencilik', 'gcl', 'sea',
              'ministry', 'harbin', 'iranian', 'securities', 'ii', 'jinan', 'san', 'rizhao',
              'hongyuan', 'texas', 'shell', 'vietnam', 'tica', 'gulf', 'association', 'jiexiu',
              'carbon', 'weihai', 'lestari', 'nigeria', 'free', 'canada', 'petrochina', 'business',
              'guohua', 'huizhou', 'gazprom',
              'linfen', 'private', 'oilfield', 'perkasa', 'department', 'xinyuan', 'biological', 'yili', 'xinhui', 'makmur',
              'shouguang', 'heavy', 'fuxin', 'zhongshan', 'changqing', 'yuyang', 'northern',
              'region', 'land', 'karya', 'valley',
              'western', 'century', 'sunshine', 'long', 'cnooc', 'delta', 'golden', 'shouyang', 'heating',
              'xin', 'yantai', 'dongfang', 'pcl', 'huarun', 'shenneng', 'science', 'totalenergies', 'liansheng', 'institute',
              'weifang', 'american', 'shanyin', 'export', 'fushun', 'bp', 'persada', 'division', 'africa', 'hongda', 'comprehensive',
              'integrated', 'foshan', 'eastern', 'great', 'corps', 'mitsui', 'binzhou',
               'nanyang', 'offshore', 'pulp', 'gangue', 'dongsheng', 'plus', 'waste', 'sp', 'da',
              'zezhou', 'sejahtera', 'factory', 'ecological', 'mill', 'machinery',
               'abadi', 'tibet', 'railway', 'sas', 'hongxing', 'huarong', 'h', 'yangtai', 'qujing', 'complex','companhia', 'jinyuan', 'otog', 'xinneng',
              'zaozhuang', 'projects', 'shaoxing', 'demir', 'pu', 'nickel', 'pratama', 'shakhta', 'kailuan', 'systems', 'wuxi', 'huozhou', 'taicang', 'anyang',
              'yichang', 'star', 'es', 'permian', 'rongcheng', 'handan', 'pingdingshan', 'chengdu', 'sdic', 'yan', 'ad', 'zhongtai',
              'second', 'republic', 'jingneng', 'eagle','ocean', 'korea', 'coastal', 'sucursal', 'lng', 'yangzhou', 'tian',
               'ojsc', 'egyptian', 'tianan', 'first', 'hami', 'bay', 'yicheng', 'norte','huayuan', 'puyang',
               'tianyu', 'jv', 'u', 'heze', 'zavod', 'puxian', 'xishan', 'nusantara', 'hengyuan', 'tianyuan',
               'yanchang', 'fengyuan', 'peabody', 'zhongyang', 'forest', 'trica', 'contracting', 'chifeng', 'empresa', 'brothers',
              'xintai','jining','overseas', 'changxing', 'three', 'changzhou', 'shijiazhuang',
               'mills', 'arcelormittal','xinyang', 'yuxian', 'sun', 'township', 'zuoquan', 'collective','hengshan', 'heshun', 'distribution', 'clp', 'nantong', 'heat',
              'taishan', 'gen', 'fuyuan', 'oriental', 'tpp', 'yidong', 'summit','lanhua', 'board', 'hope', 'huineng', 'chevron', 'shougang', 'inner', 'celik']

In [ ]:
import re

# Define the pattern for removing suffixes
pattern = r'\b(' + '|'.join(re.escape(suffix) for suffix in removal_list) + r')\b'

# Combine all cleaning steps, modifying the problematic line
mapped_df.loc[:, 'NAME_CLEANED'] = (
    mapped_df['NAME']
    .str.lower()  # Convert to lowercase
    .str.replace(r'[^\x00-\x7F]', '', regex=True)  # Replace non-ASCII characters with space
    .str.replace(r'[^a-zA-Z0-9\s]', '', regex=True)  # Replace special characters
    .str.replace(pattern, '', regex=True)  # Replace suffixes
    .str.replace('[.,]', '', regex=True)  # Replace commas and periods
    .str.strip()  # Remove leading and trailing spaces
)

# remove non-ASCII rows
mapped_df = mapped_df[mapped_df['NAME_CLEANED'] != '']

In [ ]:
mapped_df

,NAME,INDUSTRY,SIZE,INDUSTRY_GROUP,NAME_CLEANED
0,mt warren park,"health, wellness and fitness",1-10,Healthcare & Wellness,mt warren
1,new vanden borre transport,package/freight delivery,1-10,Other,vanden borre transport
2,dominage steel building systems ltd.,construction,51-200,Construction & Real Estate,dominage steel building
3,rajshree engineering pvt. ltd.,mining & metals,1-10,Resources,rajshree engineering
4,hobbs groundworks ltd,civil engineering,1-10,Manufacturing & Engineering,hobbs groundworks
...,...,...,...,...,...
18489764,tucker elementary school,e-learning,11-50,Education & Training,tucker elementary school
18489765,susan marie llc,retail,1-10,Retail & Consumer Goods,susan marie
18489766,el morro scm,retail,1-10,Retail & Consumer Goods,morro scm
18489767,"tigear, inc.",sporting goods,1-10,Other,tigear
18489768,zeuligan computers,computer hardware,1-10,Other,zeuligan computers

In [ ]:
mapped_df.isnull().sum()

NAME              4
INDUSTRY          0
SIZE              0
INDUSTRY_GROUP    0
NAME_CLEANED      4
dtype: int64

In [ ]:
mapped_df[mapped_df["NAME_CLEANED"].isnull()]

         NAME           INDUSTRY   SIZE           INDUSTRY_GROUP NAME_CLEANED
3211157   NaN  computer software  11-50          Technology & IT          NaN
10142267  NaN       supermarkets   1-10                    Other          NaN
11293388  NaN  apparel & fashion   1-10  Retail & Consumer Goods          NaN
12294210  NaN  computer software   1-10          Technology & IT          NaN

In [ ]:
mapped_df.dropna(inplace = True)

<ipython-input-9-4d50c369e5a5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mapped_df.dropna(inplace = True)

In [ ]:
mapped_df["NAME_CLEANED"].isnull().sum()

0

In [ ]:
mapped_df.to_csv('/content/drive/MyDrive/forward_analytics_results/mapped_company')